version: '3'

networks:
  network_app:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - network_app
    command: >
      sh -c "composer install &&
             php artisan migrate --force &&
             php artisan news:fetch &&
             php artisan serve --host=0.0.0.0 --port=8000"

  postgres:
    image: postgres:12.3-alpine
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - network_app